#!/usr/bin/env bash
set -euo pipefail

# One-off migration helper for legacy hotfix directories.
#
# What it does:
# - scans directories under ROOT
# - finds legacy files matching: CVE-YYYY-NNNN-*.sh
# - groups them only if:
#     * suffix after CVE is the same
#     * file content is identical
# - tries to infer a better hotfix id from script content
# - writes/updates index.yaml for the new resolver
# - does NOT delete or rename any legacy files
#
# Default mode is dry-run.
#
# Environment variables:
#   ROOT=hotfixes                 root directory to scan
#   WRITE=0|1                     actually write files
#   INCLUDE_SINGLETONS=0|1        include groups with only one legacy file
#   REPLACE_GENERATED=0|1         replace only blocks previously generated by this script
#   BACKUP_EXISTING=0|1           create index.yaml.bak before overwrite
#   VERBOSE=0|1                   verbose logs
#
# Recommended first run:
#   bash ./migrate-hotfixes.sh
#
# Actual write:
#   WRITE=1 bash ./migrate-hotfixes.sh
#
# Single subtree:
#   ROOT=hotfixes/alpine/3.23.3 WRITE=1 bash ./migrate-hotfixes.sh

ROOT="${ROOT:-hotfixes}"
WRITE="${WRITE:-0}"
INCLUDE_SINGLETONS="${INCLUDE_SINGLETONS:-0}"
REPLACE_GENERATED="${REPLACE_GENERATED:-1}"
BACKUP_EXISTING="${BACKUP_EXISTING:-1}"
VERBOSE="${VERBOSE:-0}"

if ! command -v sha256sum >/dev/null 2>&1; then
  echo "ERROR: sha256sum is required" >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 is required" >&2
  exit 1
fi

tmp_root="$(mktemp -d)"
trap 'rm -rf "$tmp_root"' EXIT

log() {
  printf '%s\n' "$*" >&2
}

vlog() {
  if [[ "$VERBOSE" == "1" ]]; then
    printf '%s\n' "$*" >&2
  fi
}

sanitize_id() {
  local s="$1"
  s="$(printf '%s' "$s" | tr '[:upper:]' '[:lower:]')"
  s="$(printf '%s' "$s" | sed -E 's/[^a-z0-9._+-]+/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g')"
  printf '%s\n' "$s"
}

extract_package_candidates_from_apk_line() {
  local line="$1"

  python3 - "$line" <<'PY'
import shlex
import sys

line = sys.argv[1]

try:
    tokens = shlex.split(line, posix=True)
except Exception:
    print("")
    sys.exit(0)

if not tokens:
    print("")
    sys.exit(0)

# Find apk verb position.
# Accept:
#   apk add ...
#   /sbin/apk add ...
#   command apk add ...
verb_idx = None
verb = None

for i, tok in enumerate(tokens):
    base = tok.rsplit("/", 1)[-1]
    if base == "apk" and i + 1 < len(tokens):
        nxt = tokens[i + 1]
        if nxt in {"add", "fix", "del"}:
            verb_idx = i + 1
            verb = nxt
            break

if verb_idx is None:
    print("")
    sys.exit(0)

skip_next = False
packages = []

# Options whose next token is a value.
opts_with_value = {
    "--repository",
    "--virtual",
    "--root",
    "--keys-dir",
    "--repositories-file",
    "--allow-untrusted",
    "--arch",
    "--initdb",
    "--progress",
    "--cache-dir",
    "--wait",
    "--timeout",
}

for tok in tokens[verb_idx + 1:]:
    if skip_next:
        skip_next = False
        continue

    if tok == ";":
        break

    if tok in opts_with_value:
        skip_next = True
        continue

    if tok.startswith("-"):
        continue

    # Very conservative filter.
    # Treat a token as package-ish if it is not shell syntax and not an assignment.
    if tok in {"&&", "||", "|", "\\", "then", "do", "fi", "done"}:
        break

    if "=" in tok:
        # pkg=version form
        pkg = tok.split("=", 1)[0].strip()
        ver = tok.split("=", 1)[1].strip()
        if pkg:
            packages.append((pkg, ver))
        continue

    packages.append((tok.strip(), ""))

# Emit TSV-like lines so bash can read them.
for pkg, ver in packages:
    print(f"{pkg}\t{ver}")
PY
}

guess_hotfix_id() {
  local file="$1"
  local suffix="$2"

  local action=""
  local apk_line=""
  local line=""

  while IFS= read -r line || [[ -n "$line" ]]; do
    # Strip leading spaces for simpler matching.
    line="${line#"${line%%[![:space:]]*}"}"

    [[ -z "$line" ]] && continue
    [[ "$line" =~ ^# ]] && continue

    if [[ "$line" == *"apk add"* ]]; then
      apk_line="$line"
      if [[ "$line" == *"--upgrade"* ]]; then
        action="apk-upgrade"
      else
        action="apk-install"
      fi
      break
    fi

    if [[ "$line" == *"apk fix"* ]]; then
      apk_line="$line"
      action="apk-fix"
      break
    fi

    if [[ "$line" == *"apk del"* ]]; then
      apk_line="$line"
      action="apk-remove"
      break
    fi
  done < "$file"

  if [[ -z "$apk_line" || -z "$action" ]]; then
    printf 'legacy-%s\n' "$(sanitize_id "$suffix")"
    return 0
  fi

  local -a candidates=()
  local pkg ver
  while IFS=$'\t' read -r pkg ver; do
    [[ -z "${pkg:-}" ]] && continue
    candidates+=("$pkg"$'\t'"$ver")
  done < <(extract_package_candidates_from_apk_line "$apk_line")

  if [[ "${#candidates[@]}" -eq 0 ]]; then
    printf 'legacy-%s\n' "$(sanitize_id "$suffix")"
    return 0
  fi

  if [[ "${#candidates[@]}" -gt 1 ]]; then
    printf '%s-batch-%s\n' "$action" "$(sanitize_id "$suffix")"
    return 0
  fi

  pkg="${candidates[0]%%$'\t'*}"
  ver="${candidates[0]#*$'\t'}"

  pkg="$(sanitize_id "$pkg")"
  ver="$(sanitize_id "$ver")"

  if [[ -n "$ver" ]]; then
    printf '%s-%s-%s\n' "$action" "$pkg" "$ver"
  else
    printf '%s-%s\n' "$action" "$pkg"
  fi
}

collect_group_data() {
  local dir="$1"
  local out_tsv="$2"

  : > "$out_tsv"

  local -a files=()
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$dir" -maxdepth 1 -type f -name 'CVE-*-*.sh' -print0 | sort -z)

  if [[ "${#files[@]}" -eq 0 ]]; then
    return 0
  fi

  local f base cve suffix hash guessed_id
  for f in "${files[@]}"; do
    base="$(basename "$f")"

    if [[ ! "$base" =~ ^(CVE-[0-9]{4}-[0-9]+)-(.*)\.sh$ ]]; then
      continue
    fi

    cve="${BASH_REMATCH[1]}"
    suffix="${BASH_REMATCH[2]}"
    hash="$(sha256sum "$f" | awk '{print $1}')"
    guessed_id="$(guess_hotfix_id "$f" "$suffix")"

    printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
      "$suffix" "$hash" "$cve" "$base" "$f" "$guessed_id" >> "$out_tsv"
  done
}

build_generated_block() {
  local data_tsv="$1"
  local include_singletons="$2"
  local out_yaml="$3"

  python3 - "$data_tsv" "$include_singletons" > "$out_yaml" <<'PY'
import sys
from collections import defaultdict

data_tsv = sys.argv[1]
include_singletons = sys.argv[2] == "1"

groups = defaultdict(list)

with open(data_tsv, "r", encoding="utf-8") as fh:
    for raw in fh:
        raw = raw.rstrip("\n")
        if not raw:
            continue
        suffix, sha, cve, base, path, guessed_id = raw.split("\t")
        groups[(suffix, sha)].append({
            "suffix": suffix,
            "sha": sha,
            "cve": cve,
            "base": base,
            "path": path,
            "guessed_id": guessed_id,
        })

def yaml_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"

selected = []
used_ids = set()

for (suffix, sha), items in sorted(groups.items(), key=lambda x: (x[0][0], x[0][1])):
    items = sorted(items, key=lambda x: x["base"])

    if len(items) == 1 and not include_singletons:
        continue

    proposed_id = items[0]["guessed_id"].strip()
    if not proposed_id:
        proposed_id = f"legacy-{suffix}"

    final_id = proposed_id
    n = 2
    while final_id in used_ids:
        final_id = f"{proposed_id}-{n}"
        n += 1
    used_ids.add(final_id)

    selected.append({
        "id": final_id,
        "file": items[0]["base"],
        "cves": sorted({item["cve"] for item in items}),
        "legacy_files": [item["base"] for item in items],
        "suffix": suffix,
        "sha": sha,
        "group_size": len(items),
    })

for item in selected:
    print("# BEGIN AUTO-GENERATED HOTFIX")
    print("# generator: legacy-cve-grouping-v2")
    print(f"# source_suffix: {item['suffix']}")
    print(f"# content_sha256: {item['sha']}")
    print(f"# group_size: {item['group_size']}")
    print(f"# legacy_files: {', '.join(item['legacy_files'])}")
    print(f"- id: {yaml_quote(item['id'])}")
    print(f"  file: {yaml_quote(item['file'])}")
    print("  match:")
    print("    cves:")
    for cve in item["cves"]:
        print(f"      - {yaml_quote(cve)}")
    print("# END AUTO-GENERATED HOTFIX")
PY
}

strip_previous_generated_blocks() {
  local src="$1"
  local dst="$2"

  awk '
    BEGIN { skip=0 }
    /^# BEGIN AUTO-GENERATED HOTFIX$/ { skip=1; next }
    /^# END AUTO-GENERATED HOTFIX$/   { skip=0; next }
    skip == 0 { print }
  ' "$src" > "$dst"
}

normalize_existing_index() {
  local src="$1"
  local dst="$2"

  if [[ ! -s "$src" ]]; then
    printf 'hotfixes:\n' > "$dst"
    return 0
  fi

  if grep -q '^hotfixes:[[:space:]]*$' "$src"; then
    cp "$src" "$dst"
  else
    {
      printf 'hotfixes:\n'
      cat "$src"
    } > "$dst"
  fi
}

append_generated_entries() {
  local base_yaml="$1"
  local generated_yaml="$2"
  local out_yaml="$3"

  cp "$base_yaml" "$out_yaml"

  if [[ ! -s "$generated_yaml" ]]; then
    return 0
  fi

  # Ensure there is a trailing newline before append.
  if [[ -n "$(tail -c 1 "$out_yaml" 2>/dev/null || true)" ]]; then
    printf '\n' >> "$out_yaml"
  fi

  cat "$generated_yaml" >> "$out_yaml"
}

process_dir() {
  local dir="$1"
  local index_file="$dir/index.yaml"

  local data_tsv="$tmp_root/data.$RANDOM.tsv"
  local generated_yaml="$tmp_root/generated.$RANDOM.yaml"
  local stripped_yaml="$tmp_root/stripped.$RANDOM.yaml"
  local normalized_yaml="$tmp_root/normalized.$RANDOM.yaml"
  local final_yaml="$tmp_root/final.$RANDOM.yaml"

  collect_group_data "$dir" "$data_tsv"

  if [[ ! -s "$data_tsv" ]]; then
    return 0
  fi

  log "[dir] $dir"

  local legacy_count
  legacy_count="$(wc -l < "$data_tsv" | tr -d ' ')"
  log "  legacy entries: $legacy_count"

  build_generated_block "$data_tsv" "$INCLUDE_SINGLETONS" "$generated_yaml"

  local generated_count
  generated_count="$(grep -c '^# BEGIN AUTO-GENERATED HOTFIX$' "$generated_yaml" || true)"

  if [[ "$generated_count" -eq 0 ]]; then
    log "  no generated entries"
    return 0
  fi

  if [[ -f "$index_file" ]]; then
    if [[ "$REPLACE_GENERATED" == "1" ]]; then
      strip_previous_generated_blocks "$index_file" "$stripped_yaml"
    else
      cp "$index_file" "$stripped_yaml"
    fi
  else
    : > "$stripped_yaml"
  fi

  normalize_existing_index "$stripped_yaml" "$normalized_yaml"
  append_generated_entries "$normalized_yaml" "$generated_yaml" "$final_yaml"

  log "  generated entries: $generated_count"

  if [[ "$VERBOSE" == "1" ]]; then
    python3 - "$data_tsv" <<'PY'
import sys
from collections import defaultdict

path = sys.argv[1]
groups = defaultdict(list)
with open(path, "r", encoding="utf-8") as fh:
    for line in fh:
        suffix, sha, cve, base, full, guessed_id = line.rstrip("\n").split("\t")
        groups[(suffix, sha)].append((cve, base, guessed_id))

for (suffix, sha), items in sorted(groups.items()):
    items = sorted(items)
    print(f"    group suffix={suffix} sha={sha[:12]} count={len(items)} guessed_id={items[0][2]}", file=sys.stderr)
    for cve, base, _ in items:
        print(f"      - {cve} -> {base}", file=sys.stderr)
PY
  fi

  if [[ "$WRITE" == "1" ]]; then
    if [[ -f "$index_file" && "$BACKUP_EXISTING" == "1" ]]; then
      cp "$index_file" "$index_file.bak"
      log "  backup: $index_file.bak"
    fi
    mv "$final_yaml" "$index_file"
    log "  wrote: $index_file"
  else
    log "  dry-run: would write $index_file"
    sed 's/^/    /' "$final_yaml" >&2
  fi
}

main() {
  if [[ ! -d "$ROOT" ]]; then
    echo "ERROR: ROOT directory does not exist: $ROOT" >&2
    exit 1
  fi

  local -a dirs=()
  while IFS= read -r -d '' d; do
    dirs+=("$d")
  done < <(find "$ROOT" -type d -print0 | sort -z)

  if [[ "${#dirs[@]}" -eq 0 ]]; then
    echo "ERROR: No directories found under ROOT=$ROOT" >&2
    exit 1
  fi

  local d
  for d in "${dirs[@]}"; do
    process_dir "$d"
  done
}

main "$@"