#!/usr/bin/env python3
from __future__ import annotations

import html
import json
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]

REPO = "rafalmasiarek/php-images"
SITE_BASE_URL = "https://php-images.masiarek.dev"


def detect_alpine(dockerfile: Path) -> str:
    txt = dockerfile.read_text(encoding="utf-8", errors="replace")
    from_line = ""
    for line in txt.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.upper().startswith("FROM "):
            from_line = line
            break
    if not from_line:
        return "unknown"

    m = re.search(r"\balpine:(\d+(?:\.\d+)*)\b", from_line)
    if m:
        return m.group(1)

    m = re.search(r"\balpine(\d+(?:\.\d+)*)\b", from_line)
    if m:
        return m.group(1)

    return "unknown"


def php_key(s: str) -> tuple[int, ...]:
    try:
        return tuple(int(x) for x in s.split("."))
    except Exception:
        return (0,)


def badge_img(url: str, alt: str) -> str:
    return f'<img src="{html.escape(url)}" alt="{html.escape(alt)}" loading="lazy" />'


def shields_endpoint_badge(endpoint_url: str, alt: str) -> str:
    shields = "https://img.shields.io/endpoint?url=" + quote(endpoint_url, safe="")
    return badge_img(shields, alt)


def trivy_badge(php: str, variant: str) -> str:
    endpoint_url = f"{SITE_BASE_URL}/badges/trivy-{php}-{variant}.json"
    return shields_endpoint_badge(endpoint_url, f"trivy {php}-{variant}")


def trivy_report_link(php: str, variant: str) -> str:
    url = f"{SITE_BASE_URL}/reports/trivy-{php}-{variant}.html"
    return f'<a href="{html.escape(url)}" target="_blank" rel="noopener">report</a>'


def os_badge_html(alpine_version: str) -> str:
    """
    Shields static badge that links to Docker Hub layers page:
    https://hub.docker.com/layers/library/alpine/X.XX
    """
    if not alpine_version or alpine_version == "unknown":
        url = "https://img.shields.io/badge/" + quote("alpine-unknown-lightgrey", safe="")
        return badge_img(url, "alpine")

    label = "alpine"
    message = f"v{alpine_version}"
    color = "blue"
    url = "https://img.shields.io/badge/" + quote(f"{label}-{message}-{color}", safe="")
    link = f"https://hub.docker.com/layers/library/alpine/{alpine_version}"
    return f'<a href="{html.escape(link)}" target="_blank" rel="noopener">{badge_img(url, "alpine")}</a>'


def release_url_for_php(php: str) -> str:
    return f"https://github.com/{REPO}/releases/tag/php-{php}"


def load_last_build(php: str) -> tuple[str, str]:
    """
    Reads web/badges/last-<php>.json generated by workflow.
    Returns (date, sha7). If missing/invalid, returns ("-", "-").
    """
    p = ROOT / "web" / "badges" / f"last-{php}.json"
    if not p.exists():
        return "-", "-"
    try:
        obj = json.loads(p.read_text(encoding="utf-8"))
        date = str(obj.get("date") or "-")
        sha = str(obj.get("sha") or "-")
        return date or "-", sha or "-"
    except Exception:
        return "-", "-"


# Collect versions data from versions/*/*/Dockerfile
data: dict[str, dict[str, dict[str, str]]] = {}

for dockerfile in sorted((ROOT / "versions").glob("*/*/Dockerfile")):
    php = dockerfile.parts[-3]
    variant = dockerfile.parts[-2]
    tag = f"{php}-{variant}"
    data.setdefault(php, {})
    data[php][variant] = {
        "tag": tag,
        "os": detect_alpine(dockerfile),
    }


html_out: list[str] = []

html_out.append("<table>")
html_out.append(
    "<thead><tr>"
    "<th>PHP</th>"
    "<th>Last build</th>"
    "<th>SHA</th>"
    "<th>Tags</th>"
    "<th>OS</th>"
    "<th>Trivy</th>"
    "</tr></thead>"
)
html_out.append("<tbody>")

for php in sorted(data.keys(), key=php_key):
    variants = data[php]
    variant_names = sorted(variants.keys())

    last_date, last_sha = load_last_build(php)

    php_cell = (
        f'<a href="{html.escape(release_url_for_php(php))}" target="_blank" rel="noopener">'
        f"<code>{html.escape(php)}</code></a>"
    )

    tags_lines: list[str] = []
    os_lines: list[str] = []
    trivy_lines: list[str] = []

    for v in variant_names:
        tag = variants[v]["tag"]
        os_ver = variants[v]["os"]

        tags_lines.append(f"<strong>{html.escape(v)}</strong>: <code>{html.escape(tag)}</code>")
        os_lines.append(f"<strong>{html.escape(v)}</strong>: {os_badge_html(os_ver)}")
        trivy_lines.append(
            f"<strong>{html.escape(v)}</strong>: "
            f"{trivy_badge(php, v)} "
            f"({trivy_report_link(php, v)})"
        )

    html_out.append("<tr>")
    html_out.append(f"<td>{php_cell}</td>")
    html_out.append(f"<td><code>{html.escape(last_date)}</code></td>")
    html_out.append(f"<td><code>{html.escape(last_sha)}</code></td>")
    html_out.append(f"<td>{'<br>'.join(tags_lines)}</td>")
    html_out.append(f"<td>{'<br>'.join(os_lines)}</td>")
    html_out.append(f"<td>{'<br>'.join(trivy_lines)}</td>")
    html_out.append("</tr>")

html_out.append("</tbody></table>")

out = ROOT / "web" / "_includes" / "generated-table.html"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(html_out) + "\n", encoding="utf-8")
print(f"Wrote {out}")
